version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:

  mysql_db:
    image: mysql:5.7
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: gatodeportivo
      MYSQL_DATABASE: employex

  python_app:
    image: python:latest
    ports:
      - "8080:8080"
    volumes:
      - type: 'bind'
        source: .
        target: /scripts
    command: tail -f /dev/null
    links:
      - 'mysql_db'