version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:

  mysql_db:
    image: mysql:5.7
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: gatodeportivo
      MYSQL_DATABASE: employex
    ports:
      - "3306:3306"
      
  python_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db